<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 7.1 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.1</h1>
<h3>Aufbau eines fiktiven Pizza Moduls</h3>
<pre>
/
    module/
        Pizza/
            Module.php
            autoload_classmap.php
            autoload_function.php
            autoload_register.php
            config/
                module.config.php
            public/
                pizza/
                    images/
                    css/
                    js/
            src/
                Pizza/
                    Controller/
                    Filter/
                    Form/
                    View/
                        Helper/
            test/
                phpunit.xml
                bootstrap.php
                PizzaTest/
                    Controller/
                    Filter/
                    Form/
                    View/
                        Helper/
            view/
                pizza/
                    index/
                        index.phtml
                        show.phtml
                    admin/
                        index.phtml
                        show.phtml
                        create.phtml
                        update.phtml
</pre>
</div>
</div>
