<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 7.7 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.7</h1>
<h3>View-Helper konfigurieren mit <code>getViewHelperConfig()</code></h3>
<pre>
&lt;?php 
namespace Pizza;

use Zend\ModuleManager\Feature\ViewHelperProviderInterface;

class Module implements ViewHelperProviderInterface
{
    public function getViewHelperConfig()
    {
        return array(
            'invokables' => array(
                'url' => 'Pizza\View\Helper\Url',
            ),
            'factories' => array(
                'pizzaAvailable' => 'Pizza\View\Helper\IsAvailableFactory',
            ),
        );
    }
}
</pre>
</div>
</div>
