<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 7.14 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.14</h1>
<h3>View-Skript für Pizzaseite vom <code>Pizza</code> Modul</h3>
<pre>
&lt;div class="hero-unit"&gt;
&lt;h1&gt;Hallo Pizza &lt;?php echo $this-&gt;escapeHtml($this-&gt;pizzaName); ?&gt;!&lt;/h1&gt;
&lt;/div&gt;
&lt;div class="span3"&gt;
&lt;p&gt;
&lt;a class="btn" href="&lt;?php echo $this-&gt;url('pizza'); ?&gt;"&gt;
Zurück zur Übersicht
&lt;/a&gt;
&lt;/p&gt;
&lt;/div&gt;
</pre>
</div>
</div>
