<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 7.16 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.16</h1>
<h3>View-Helper für die Anzeige der »Hallo Pizza« Begrüßung</h3>
<pre>
namespace LuigiLib\View\Helper;

use Zend\Form\View\Helper\AbstractHelper;

class HelloPizza extends AbstractHelper
{
    public function __invoke()
    {
        return 'Hallo Pizza!!!';
    }
}

</pre>
</div>
</div>
