<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 7.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.12</h1>
<h3>View-Skript für Startseite vom <code>Pizza</code> Modul</h3>
<pre>
&lt;div class="hero-unit"&gt;
&lt;h1&gt;Hallo Pizza!&lt;/h1&gt;
&lt;/div&gt;
&lt;div class="row"&gt;
&lt;?php foreach ($this-&gt;pizzaList as $pizza) :?&gt;
&lt;?php $url = $this-&gt;url('pizza-name', array('name' =&gt; $pizza));?&gt;
&lt;div class="span3"&gt;
&lt;p&gt;
&lt;a class="btn btn-primary" href="&lt;?php echo $url; ?&gt;"&gt;
Pizza &lt;?php echo $pizza; ?&gt;
&lt;/a&gt;
&lt;/p&gt;
&lt;/div&gt;
&lt;?php endforeach;?&gt;
&lt;/div&gt;
</pre>
</div>
</div>
