<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 7.8 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.8</h1>
<h3>Modul-Klasse für das <code>Pizza</code> Modul</h3>
<pre>
&lt;?php 
namespace Pizza;

use Zend\EventManager\EventInterface;
use Zend\ModuleManager\Feature\BootstrapListenerInterface;

class Module implements BootstrapListenerInterface
{
    public function onBootstrap(EventInterface $e)
    {
        echo '&lt;div class="container"&gt;';
        echo '&lt;div class="hero-unit"&gt;';
        echo '&lt;h1&gt;Hallo Pizza!&lt;/h1&gt;';
        echo '&lt;/div&gt;';
        echo '&lt;/div&gt;';
    }
}
</pre>
</div>
</div>
