<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 7.18 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.18</h1>
<h3>Datenbankkonfiguration für ZfcUser</h3>
<pre>
&lt;\?php
$parms = array(
    'database'  => 'zf2buch07',
    'username'  => 'zf2buch07',
    'password'  => 'zf2buch07',
    'hostname'  => 'localhost',
);

return array(
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => function ($sm) use ($parms) {
                return new Zend\Db\Adapter\Adapter(array(
                    'driver'    => 'pdo',
                    'dsn'       => 'mysql:dbname='.$parms['database'].';host='.$parms['hostname'],
                    'database'  => $parms['database'],
                    'username'  => $parms['username'],
                    'password'  => $parms['password'],
                    'hostname'  => $parms['hostname'],
                ));
            },
        ),
    ),
);
</pre>
</div>
</div>
