<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 7.8 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.8</h1>
<h3>Modul-Konfiguration für das <code>Pizza</code> Modul</h3>
<pre>
&lt;?php 
return array(
    'router' => array(
        'routes' => array(
            'pizza' => array(
                'type' => 'Literal',
                'options' => array(
                    'route'    => '/pizza',
                    'defaults' => array(
                        'controller' => 'pizza',
                        'action'     => 'index',
                    ),
                ),
            ),
            'pizza-name' => array(
                'type'    => 'segment',
                'options' => array(
                    'route'    => '/pizza/:name',
                    'constraints' => array(
                        'name' => '[A-Z][a-zA-Z-]*',
                    ),
                    'defaults' => array(
                        'controller' => 'pizza',
                        'action'     => 'name',
                    ),
                ),
            ),
        ),
    ),
    
    'controllers' => array(
        'invokables' => array(
            'pizza'   => 'Pizza\Controller\IndexController',
        ),
    ),
    
    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
);
</pre>
</div>
</div>
