<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 7.13 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 7.13</h1>
<h3>Erweiterter <code>IndexController</code> für das <code>Pizza</code> Modul</h3>
<pre>
namespace Pizza\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    public function indexAction()
    {
        $pizzaList = array(
            'Salami', 'Hawaii', 'Melone', 'Schinken', 'Thunfisch',
            'Speziale', 'Calzone', 'Vierjahreszeiten', 'Spinat',
        );
        
        return new ViewModel(array(
            'pizzaList' => $pizzaList
        ));
    }
    
    public function nameAction()
    {
        $pizzaName = $this->params()->fromRoute('name');
        
        return new ViewModel(array(
            'pizzaName' => $pizzaName
        ));
    }
}
</pre>
</div>
</div>
