<?php 
/**
 * ZF2 Buch Kapitel 7
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 7</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0701">Listing 7.1</a></td>
<td>Aufbau eines fiktiven Pizza Moduls</td>
</tr>
<tr>
<td><a href="/listing/listing0702">Listing 7.2</a></td>
<td>Modul-Konfiguration des Autoloadings mit <code>getAutoloaderConfig()</code></td>
</tr>
<tr>
<td><a href="/listing/listing0703">Listing 7.3</a></td>
<td>Konfigurationsdaten für Modul mit <code>getConfig()</code> einlesen</td>
</tr>
<tr>
<td><a href="/listing/listing0704">Listing 7.4</a></td>
<td>Konfiguration für Services mit <code>getServiceConfig()</code> bereitstellen</td>
</tr>
<tr>
<td><a href="/listing/listing0705">Listing 7.5</a></td>
<td>Konfiguration für Controller mit <code>getControllerConfig()</code> bereitstellen</td>
</tr>
<tr>
<td><a href="/listing/listing0706">Listing 7.6</a></td>
<td>Controller-Plugins konfigurieren mit <code>getControllerPluginConfig()</code></td>
</tr>
<tr>
<td><a href="/listing/listing0707">Listing 7.7</a></td>
<td>View-Helper konfigurieren mit <code>getViewHelperConfig()</code></td>
</tr>
<tr>
<td><a href="/listing/listing0708">Listing 7.8</a></td>
<td>Modul-Klasse für das <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0709">Listing 7.9</a></td>
<td>Modul-Konfiguration für das <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0710">Listing 7.10</a></td>
<td>Modul-Klasse mit <code>getConfig()</code> und <code>getAutoloaderConfig()</code> Methoden</td>
</tr>
<tr>
<td><a href="/listing/listing0711">Listing 7.11</a></td>
<td><code>IndexController</code> für das <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0712">Listing 7.12</a></td>
<td>View-Skript für Startseite vom <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0713">Listing 7.13</a></td>
<td>Erweiterter <code>IndexController</code> für das <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0714">Listing 7.14</a></td>
<td>View-Skript für Pizzaseite vom <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0715">Listing 7.15</a></td>
<td>Modul-Klasse für Library Anwendungsmodul</td>
</tr>
<tr>
<td><a href="/listing/listing0716">Listing 7.16</a></td>
<td>View-Helper für die Anzeige der »Hallo Pizza« Begrüßung</td>
</tr>
<tr>
<td><a href="/listing/listing0717">Listing 7.17</a></td>
<td>Einsatz des neuen View-Helpers in einem View-Skript</td>
</tr>
<tr>
<td><a href="/listing/listing0718">Listing 7.18</a></td>
<td>Datenbankkonfiguration für ZfcUser</td>
</tr>
</tbody>
</table>
